/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letraunica = 5;
  /** RegularExpression Id. */
  int dig = 6;
  /** RegularExpression Id. */
  int Absoluto = 7;
  /** RegularExpression Id. */
  int Abstracto = 8;
  /** RegularExpression Id. */
  int Activar = 9;
  /** RegularExpression Id. */
  int Alias = 10;
  /** RegularExpression Id. */
  int Y = 11;
  /** RegularExpression Id. */
  int Aplicacion = 12;
  /** RegularExpression Id. */
  int Arreglo = 13;
  /** RegularExpression Id. */
  int Ascendiente = 14;
  /** RegularExpression Id. */
  int Ensamblador = 15;
  /** RegularExpression Id. */
  int Afirmar = 16;
  /** RegularExpression Id. */
  int Identificador = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<letraunica>",
    "<dig>",
    "\"abs\"",
    "\"abstract\"",
    "\"activate\"",
    "\"alias\"",
    "\"and\"",
    "\"app\"",
    "\"array\"",
    "\"ascatn\"",
    "\"asm\"",
    "\"assert\"",
    "<Identificador>",
  };

}
